{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.integration",
    "module": "spring-integration-core",
    "version": "6.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.9"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.10"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.13.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-6.3.4.jar",
          "url": "spring-integration-core-6.3.4.jar",
          "size": 1674240,
          "sha512": "26fa6d2f801fe7b082d31382a1a7bb148e6da7d046074942b816fa655294d6ac52b49201d9b46b6e53c698e60b009bbcaa309b121aa206c7f5abb3286e7d3784",
          "sha256": "e4dacb1b3155fd1f635d5f7b02b4984c4b162d710be0f79975d297b23a6d255d",
          "sha1": "c02abcc0b2e14baadbe12ed785c9aa1bc78b8ac1",
          "md5": "dafc018ece03ac318315ce65d8c45a19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.13"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.9"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.10"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.13.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-6.3.4.jar",
          "url": "spring-integration-core-6.3.4.jar",
          "size": 1674240,
          "sha512": "26fa6d2f801fe7b082d31382a1a7bb148e6da7d046074942b816fa655294d6ac52b49201d9b46b6e53c698e60b009bbcaa309b121aa206c7f5abb3286e7d3784",
          "sha256": "e4dacb1b3155fd1f635d5f7b02b4984c4b162d710be0f79975d297b23a6d255d",
          "sha1": "c02abcc0b2e14baadbe12ed785c9aa1bc78b8ac1",
          "md5": "dafc018ece03ac318315ce65d8c45a19"
        }
      ]
    },
    {
      "name": "provided",
      "attributes": {
        "dependency.scope": "provided"
      }
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-core-6.3.4-javadoc.jar",
          "url": "spring-integration-core-6.3.4-javadoc.jar",
          "size": 3441561,
          "sha512": "c229c5b2f1afbe9eb22e46007319942a7add2efe6aa41115969a9400753f9804068de256dac14d89fde0f8441929c1e23bf580db941204942d25ade97df570e8",
          "sha256": "65adcde677c1ea058483cec111c00f8c9cace95592f848a6deb8ebffc46bbb92",
          "sha1": "2636c109256c87634a635aee0a028775acfd5255",
          "md5": "4d934fdddfdcf91dd9643d39bb0b07ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-core-6.3.4-sources.jar",
          "url": "spring-integration-core-6.3.4-sources.jar",
          "size": 1239959,
          "sha512": "a0a248f673a922c2ad42eb6414b0782dd9463a70d86d3ea2282243d08a1a413bbc97dda91f5d17d13e11ef5fe57291b12eea2802e43540be5a848f4f01f81f3a",
          "sha256": "133f24dd18f8f2dbe1cb4a68865dddaa36dd5e7bbf268a6210a0b108442b37b7",
          "sha1": "5829ca0a3b635b4e5640b56b0d1ab3d2f06040a6",
          "md5": "7e656a2a2af062e6790026f486ee37a6"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.esotericsoftware",
          "module": "kryo",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.13.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.3.4"
          },
          "excludes": [
            {
              "group": "aopalliance",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.avro",
          "module": "avro",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-6.3.4.jar",
          "url": "spring-integration-core-6.3.4.jar",
          "size": 1674240,
          "sha512": "26fa6d2f801fe7b082d31382a1a7bb148e6da7d046074942b816fa655294d6ac52b49201d9b46b6e53c698e60b009bbcaa309b121aa206c7f5abb3286e7d3784",
          "sha256": "e4dacb1b3155fd1f635d5f7b02b4984c4b162d710be0f79975d297b23a6d255d",
          "sha1": "c02abcc0b2e14baadbe12ed785c9aa1bc78b8ac1",
          "md5": "dafc018ece03ac318315ce65d8c45a19"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-optional",
          "version": "6.3.4"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.esotericsoftware",
          "module": "kryo",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.13.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.3.4"
          },
          "excludes": [
            {
              "group": "aopalliance",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.avro",
          "module": "avro",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-6.3.4.jar",
          "url": "spring-integration-core-6.3.4.jar",
          "size": 1674240,
          "sha512": "26fa6d2f801fe7b082d31382a1a7bb148e6da7d046074942b816fa655294d6ac52b49201d9b46b6e53c698e60b009bbcaa309b121aa206c7f5abb3286e7d3784",
          "sha256": "e4dacb1b3155fd1f635d5f7b02b4984c4b162d710be0f79975d297b23a6d255d",
          "sha1": "c02abcc0b2e14baadbe12ed785c9aa1bc78b8ac1",
          "md5": "dafc018ece03ac318315ce65d8c45a19"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-optional",
          "version": "6.3.4"
        }
      ]
    }
  ]
}
