{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-html/0.11.0/kotlinx-html-0.11.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-html",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-js-0.11.0.klib",
          "url": "kotlinx-html-js-0.11.0.klib",
          "size": 545393,
          "sha512": "54ed1f3b4743087fabaf776c2eed1f0629cfab1c0b7536d6329ae30444944f6ccf404ef0a9969965f30ec4f805b93f0d7af1aedc46011e79eec45eebd845259a",
          "sha256": "bca6c99f274b4baa6db5fcfdbaf080265bac233ba0d001225ccc5c1bf222dbc7",
          "sha1": "68c648bf24cae8aaf2bb7311fa28bac39d48460a",
          "md5": "7746730b98ef0959b2f191ae50a4bece"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-html-js-0.11.0.klib",
          "url": "kotlinx-html-js-0.11.0.klib",
          "size": 545393,
          "sha512": "54ed1f3b4743087fabaf776c2eed1f0629cfab1c0b7536d6329ae30444944f6ccf404ef0a9969965f30ec4f805b93f0d7af1aedc46011e79eec45eebd845259a",
          "sha256": "bca6c99f274b4baa6db5fcfdbaf080265bac233ba0d001225ccc5c1bf222dbc7",
          "sha1": "68c648bf24cae8aaf2bb7311fa28bac39d48460a",
          "md5": "7746730b98ef0959b2f191ae50a4bece"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-html-js-0.11.0-sources.jar",
          "url": "kotlinx-html-js-0.11.0-sources.jar",
          "size": 61532,
          "sha512": "2fe183ee3cc5642a398ab0734f8d5cd12a69231de3465d22db4ea128c6cccd4f7efdb392d85c799e38d8dff3a601b72d0ae5745dd6d725e1353d0335ecc0bf72",
          "sha256": "76fa5a0ddb8ee9ec43af5148738c367271a8af17273a5254935ea1a5754046c8",
          "sha1": "0f8ef6f43d2236ea34d45ebf065c73db812ad84d",
          "md5": "49f24eadc0dd2ce6197163bad3a4723e"
        }
      ]
    }
  ]
}
