{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.jms",
    "module": "micronaut-jms-bom",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.activemq",
          "module": "activemq-client",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.apache.activemq",
          "module": "artemis-jakarta-client",
          "version": {
            "requires": "2.41.0"
          }
        },
        {
          "group": "jakarta.jms",
          "module": "jakarta.jms-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-activemq-artemis",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-activemq-classic",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-core",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-sqs",
          "version": {
            "requires": "4.3.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.activemq",
          "module": "activemq-client",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.apache.activemq",
          "module": "artemis-jakarta-client",
          "version": {
            "requires": "2.41.0"
          }
        },
        {
          "group": "jakarta.jms",
          "module": "jakarta.jms-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-activemq-artemis",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-activemq-classic",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-core",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.micronaut.jms",
          "module": "micronaut-jms-sqs",
          "version": {
            "requires": "4.3.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-jms-bom-4.3.0.toml",
          "url": "micronaut-jms-bom-4.3.0.toml",
          "size": 1208,
          "sha512": "8088df971d376b439d9e3d24a2494a29dabfc7e2a8d50344e76aea0de5aa9a6898830fa7cf4fe00d1afd99e94149e66719e5ff515e571489d3f8ce4b75f225e2",
          "sha256": "e987d22678159e3f4e5815d4128c4bbe6a7d7f455d526923beddb9adc4176a5a",
          "sha1": "8f068f5c693d7604f1a60b70e12faa59d4f37534",
          "md5": "adc8c94f42806f636a18621029482e8b"
        }
      ]
    }
  ]
}
