{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-core",
    "version": "2.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.14.3.jar",
          "url": "jackson-core-2.14.3.jar",
          "size": 473081,
          "sha512": "7907fbde57f1ebd18d0935d34c5c9657e7dcff924c540b6ba732f87ed2e9e653ee499b21b464b3b74fa569d5865ffa717b8e2098d600a5f74cef4e97f39cc7d5",
          "sha256": "7ee2debad3c002e97b28b84d5f1b2044a38e780abb673948238f5bc656e2fe44",
          "sha1": "4fa101f81504ed6811bf1823270adb51a9b45ff3",
          "md5": "abb25b80cda20ddc2cd3bbd8fccd0d34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.14.3.jar",
          "url": "jackson-core-2.14.3.jar",
          "size": 473081,
          "sha512": "7907fbde57f1ebd18d0935d34c5c9657e7dcff924c540b6ba732f87ed2e9e653ee499b21b464b3b74fa569d5865ffa717b8e2098d600a5f74cef4e97f39cc7d5",
          "sha256": "7ee2debad3c002e97b28b84d5f1b2044a38e780abb673948238f5bc656e2fe44",
          "sha1": "4fa101f81504ed6811bf1823270adb51a9b45ff3",
          "md5": "abb25b80cda20ddc2cd3bbd8fccd0d34"
        }
      ]
    }
  ]
}
