{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.mqtt",
    "module": "micronaut-mqtt-bom",
    "version": "3.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.hivemq",
          "module": "hivemq-mqtt-client",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.mqttv5.client",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-hivemq",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-ssl",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqttv3",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqttv5",
          "version": {
            "requires": "3.7.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.hivemq",
          "module": "hivemq-mqtt-client",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.mqttv5.client",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-core",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-hivemq",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqtt-ssl",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqttv3",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.micronaut.mqtt",
          "module": "micronaut-mqttv5",
          "version": {
            "requires": "3.7.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-mqtt-bom-3.7.0.toml",
          "url": "micronaut-mqtt-bom-3.7.0.toml",
          "size": 1239,
          "sha512": "1971b080fff2abe197076dbe6efc6099f14a2fb5239274d4e7d01fc5332b7c9ba2256c24dc591b823f9f839db92045ea73d6fb3fb27b3fe81b8657f89ea33cbf",
          "sha256": "6b0c55687433c99b5b052eec78ce0c64740edb35f2026d17081ca5b0d1a2160a",
          "sha1": "7c3703a04c0a9aee35b91554a35403610cef0ab0",
          "md5": "5e7da50954744f20d73d98df92289e6a"
        }
      ]
    }
  ]
}
