{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.6.2/foundation-layout-1.6.2.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.2.jar",
          "url": "foundation-layout-desktop-1.6.2.jar",
          "size": 467716,
          "sha512": "49860804ae6b6abe019e439e9ccf6657d23e0ee3d9304f59777d9b729b603cf8f47a471ab69b737eabd293a260453c8e6cde59177651df39a12dfb1f0c69da32",
          "sha256": "8bb898232e0d9a8c56de51671769b73ea0a5ab526f9005de5deff34dddf5cbed",
          "sha1": "5097ce333c464364c68999bca0b5827f57eca630",
          "md5": "63ab7729935faa980b2366f30b52a7c7"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.2.jar",
          "url": "foundation-layout-desktop-1.6.2.jar",
          "size": 467716,
          "sha512": "49860804ae6b6abe019e439e9ccf6657d23e0ee3d9304f59777d9b729b603cf8f47a471ab69b737eabd293a260453c8e6cde59177651df39a12dfb1f0c69da32",
          "sha256": "8bb898232e0d9a8c56de51671769b73ea0a5ab526f9005de5deff34dddf5cbed",
          "sha1": "5097ce333c464364c68999bca0b5827f57eca630",
          "md5": "63ab7729935faa980b2366f30b52a7c7"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-desktop-1.6.2-sources.jar",
          "url": "foundation-layout-desktop-1.6.2-sources.jar",
          "size": 64530,
          "sha512": "a820941e7b205df026768889add75d710884eedf47fc5e45ed82ee1a4c9d6c50e2384d4ba571734a8fbc56bb2cdf67fdb4728a309b682e8b03ff7295ff7a58c3",
          "sha256": "87171abbae506e76a3014e1991d8394428508f4eb9968a64ffe7c82e4cff6b0c",
          "sha1": "f22b4d9833eb89a89227f38d145bd6a98c1c6ddb",
          "md5": "4abec1158a6cce502d3d38d857e3980d"
        }
      ]
    }
  ]
}