{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "5.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "glk34wm5ergk3nv4f5amzydqa4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.9.jar",
          "url": "spring-orm-5.3.9.jar",
          "size": 200261,
          "sha512": "3b5135d1c7bef933a2e2a7eb52b0cc89b19f373078a708e0da6f37e4c201169fbe988d520f3ace3c58147c4288f9b2aaa5454e189fd2f08e23c029e6c223e643",
          "sha256": "d6b29242cacfd5b8b96726ad1bb8e03a25a2c1b73ce99ae026acf775c2eff343",
          "sha1": "db37587efd6525283b53c7adc8989095e9eabc27",
          "md5": "0f4497f84fb520db24ee9ad634190420"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.9.jar",
          "url": "spring-orm-5.3.9.jar",
          "size": 200261,
          "sha512": "3b5135d1c7bef933a2e2a7eb52b0cc89b19f373078a708e0da6f37e4c201169fbe988d520f3ace3c58147c4288f9b2aaa5454e189fd2f08e23c029e6c223e643",
          "sha256": "d6b29242cacfd5b8b96726ad1bb8e03a25a2c1b73ce99ae026acf775c2eff343",
          "sha1": "db37587efd6525283b53c7adc8989095e9eabc27",
          "md5": "0f4497f84fb520db24ee9ad634190420"
        }
      ]
    }
  ]
}
