{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.aws",
    "module": "micronaut-aws-bom",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.787"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.31.66"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.787"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-serialization",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.31.66"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-apigateway",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cloudwatch-logging",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-lambda-events-serde",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-ua",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws-v2",
          "version": {
            "requires": "4.11.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.787"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.31.66"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.86.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.787"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-serialization",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.31.66"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-apigateway",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cloudwatch-logging",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-lambda-events-serde",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-ua",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws-v2",
          "version": {
            "requires": "4.11.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-aws-bom-4.11.0.toml",
          "url": "micronaut-aws-bom-4.11.0.toml",
          "size": 4351,
          "sha512": "44e83647484eaa229c781af9b2a19040c8387df9b8903fb929ccd86304e6aaf9bb528034690513a364fff454219e50f2eb722b0cb5bda830007848ad7d5da2aa",
          "sha256": "e5891563e85b8deb30c6b3f45ac1f9519c00929542206c7850858a9620ed1f5d",
          "sha1": "d248abb892198576660629c602ac01ff7bd31fc6",
          "md5": "9c76e0d4d693751f96dbe6919c7a763b"
        }
      ]
    }
  ]
}
