{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.reactor",
    "module": "micronaut-reactor-bom",
    "version": "3.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-bom",
          "version": {
            "requires": "2024.0.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.micrometer",
          "module": "context-propagation",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.micronaut.reactor",
          "module": "micronaut-reactor",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.reactor",
          "module": "micronaut-reactor-http-client",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-bom",
          "version": {
            "requires": "2024.0.7"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.micrometer",
          "module": "context-propagation",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.micronaut.reactor",
          "module": "micronaut-reactor",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.reactor",
          "module": "micronaut-reactor-http-client",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-reactor-bom-3.8.0.toml",
          "url": "micronaut-reactor-bom-3.8.0.toml",
          "size": 858,
          "sha512": "1fdff8ae15511aaa176a56fe4b9d3d6fb2623c419eadefb66d3eec78f53a856725f78b002a15f8afff4b957e7d4f9cf8ab20ee2fb957be62f9864b2a1f2d98a3",
          "sha256": "686e12c4b9b57abfd57230bbd5320f59a68efdcb0b8d92b80b13ae5f9247453f",
          "sha1": "8122fd0576dc42f1fb63e867e115472a064a3bd0",
          "md5": "3ca2f49cd88925113cb180dddb465af3"
        }
      ]
    }
  ]
}
