{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-dom-api-compat",
    "version": "1.9.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-dom-api-compat-1.9.22.klib",
          "url": "kotlin-dom-api-compat-1.9.22.klib",
          "size": 966889,
          "sha512": "2480ceb39f16f442c4caff8ea4701eb808166c6572a9a7c8518ba1af19a8fc1f061760ea49b8f954f0f8446f30a41b04e62227e591eb0727daa05384d93f46ed",
          "sha256": "80261f2b40af61894994523571d41e9c7b0adc690bf99d46e197123a0383431e",
          "sha1": "3c0ac04445c1aeec4366d69e1791cd6ad31ddc07",
          "md5": "3e9f3787bd6adfafb1c81d3a5d2a19bb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-dom-api-compat-1.9.22.klib",
          "url": "kotlin-dom-api-compat-1.9.22.klib",
          "size": 966889,
          "sha512": "2480ceb39f16f442c4caff8ea4701eb808166c6572a9a7c8518ba1af19a8fc1f061760ea49b8f954f0f8446f30a41b04e62227e591eb0727daa05384d93f46ed",
          "sha256": "80261f2b40af61894994523571d41e9c7b0adc690bf99d46e197123a0383431e",
          "sha1": "3c0ac04445c1aeec4366d69e1791cd6ad31ddc07",
          "md5": "3e9f3787bd6adfafb1c81d3a5d2a19bb"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-dom-api-compat-1.9.22-sources.jar",
          "url": "kotlin-dom-api-compat-1.9.22-sources.jar",
          "size": 70713,
          "sha512": "38753961437347a08431efd7d64e66669047c6560f1d7dc90b11d50620ba7040070a620ea5aebca3ab2017595edb2d16d20015a3c7c2341e1730a2b9bd7f2017",
          "sha256": "8cbfe9fa73f1bf018b5c38bbc35567936c295e2d1a62d80bf0aa51fa7b4a88da",
          "sha1": "8f66c7a17fe7f9e165d7d5b27870345cac786769",
          "md5": "6f43740b7a9dfc84bff764414a466a05"
        }
      ]
    }
  ]
}
