{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.6.2/runtime-1.6.2.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.6.2.jar",
          "url": "runtime-desktop-1.6.2.jar",
          "size": 1292946,
          "sha512": "49bb0a9eee2dd43ecd56a780b980bbe8c7a61a4b94e2256e72ea6a5244203ce1e164d4bc49801393ff5062a90522f71cc3c92ce13695a8e17fc7d3f7c9334d84",
          "sha256": "5bb2381d819e6b79478ed086ef8fa1be595b16c253ae9774691a4575e4bbcc4a",
          "sha1": "c404f302a4b25a425971d749c7c7ec769089a90d",
          "md5": "07f4e92bcbd210de836494d40186adf2"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.6.2.jar",
          "url": "runtime-desktop-1.6.2.jar",
          "size": 1292946,
          "sha512": "49bb0a9eee2dd43ecd56a780b980bbe8c7a61a4b94e2256e72ea6a5244203ce1e164d4bc49801393ff5062a90522f71cc3c92ce13695a8e17fc7d3f7c9334d84",
          "sha256": "5bb2381d819e6b79478ed086ef8fa1be595b16c253ae9774691a4575e4bbcc4a",
          "sha1": "c404f302a4b25a425971d749c7c7ec769089a90d",
          "md5": "07f4e92bcbd210de836494d40186adf2"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-desktop-1.6.2-sources.jar",
          "url": "runtime-desktop-1.6.2-sources.jar",
          "size": 366180,
          "sha512": "233e152c3e3ed723cb189712664df6a0a69e494fa4fb7dfdd4ab1484034a5e30da61e2015ae05ec4cce2f88439960e466d33d87ffc2bba6a75d1bd46610ef4fa",
          "sha256": "f231f736cc27b7ff4bf815ead617dc46904bd289d053567a1e466e15870205cb",
          "sha1": "5780d71eda2d85f139a6b8ce0b36c39cc2ad75e4",
          "md5": "49bebfdd4da6e19096c9b717d3fa67fa"
        }
      ]
    }
  ]
}