{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-api",
    "version": "1.9.25-1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.25-1.0.20.jar",
          "url": "symbol-processing-api-1.9.25-1.0.20.jar",
          "size": 122978,
          "sha512": "4885be8a9316eca72228044cc7e4ec2920086a64bd6ff0db95ec6cc1cf2863ead0e5bb2b1c8fed1a023202b078c172df10a80a251aaf47b6f635e585f0a3cf2f",
          "sha256": "cfae5ccc03eb4914b77a2c4e965bee64fb3822845659226eb4a5950f97c9f137",
          "sha1": "08ab3deb6242f61a0289c46a5e887ad185b72d37",
          "md5": "41c6d10fb68a6ae4fece0f3229764b5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-api-1.9.25-1.0.20.jar",
          "url": "symbol-processing-api-1.9.25-1.0.20.jar",
          "size": 122978,
          "sha512": "4885be8a9316eca72228044cc7e4ec2920086a64bd6ff0db95ec6cc1cf2863ead0e5bb2b1c8fed1a023202b078c172df10a80a251aaf47b6f635e585f0a3cf2f",
          "sha256": "cfae5ccc03eb4914b77a2c4e965bee64fb3822845659226eb4a5950f97c9f137",
          "sha1": "08ab3deb6242f61a0289c46a5e887ad185b72d37",
          "md5": "41c6d10fb68a6ae4fece0f3229764b5a"
        }
      ]
    }
  ]
}
