{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.guides",
    "module": "micronaut-guides-bom",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.asciidoctor",
          "module": "asciidoctorj",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.micronaut.guides",
          "module": "micronaut-guides",
          "version": {
            "requires": "0.1.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.asciidoctor",
          "module": "asciidoctorj",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.micronaut.guides",
          "module": "micronaut-guides",
          "version": {
            "requires": "0.1.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-guides-bom-0.1.0.toml",
          "url": "micronaut-guides-bom-0.1.0.toml",
          "size": 727,
          "sha512": "66530889720bb5bacc1aadf1881560a4ff6ea67e072df4779e14690628bcec2d0f0556db5b3afaaa71afbaf02c95318baa966b9c3517ebfe3916976c8945129b",
          "sha256": "b726c5b432684366285624d83d28cde3efb6751da8133f115e08cd0d1554a17e",
          "sha1": "382a5330f0d8b2fd77c332b95716b884cd15738d",
          "md5": "c9906bb6233d6740abbfd6db021ec68e"
        }
      ]
    }
  ]
}
