{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.testresources",
    "module": "micronaut-test-resources-bom",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.20.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.opensearch",
          "module": "opensearch-testcontainers",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "solr",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "consul",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "testcontainers",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "elasticsearch",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "hivemq",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "jdbc",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "kafka",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "localstack",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mariadb",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mongodb",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mssqlserver",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mysql",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "neo4j",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "oracle-xe",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "oracle-free",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "postgresql",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "r2dbc",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "rabbitmq",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "com.redis.testcontainers",
          "module": "testcontainers-redis",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "vault",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-build-tools",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-client",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-control-panel",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-elasticsearch",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-embedded",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-extensions-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-extensions-junit-platform",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-consul",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-vault",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hivemq",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-kafka",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-dynamodb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-s3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-sns",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-sqs",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-mongodb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-neo4j",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-opensearch",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-pool",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-rabbitmq",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-redis",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-server",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-solr",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-testcontainers",
          "version": {
            "requires": "2.9.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.20.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.opensearch",
          "module": "opensearch-testcontainers",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "solr",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "consul",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "testcontainers",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "elasticsearch",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "hivemq",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "jdbc",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "kafka",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "localstack",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mariadb",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mongodb",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mssqlserver",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "mysql",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "neo4j",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "oracle-xe",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "oracle-free",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "postgresql",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "r2dbc",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "rabbitmq",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "com.redis.testcontainers",
          "module": "testcontainers-redis",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.testcontainers",
          "module": "vault",
          "version": {
            "requires": "1.20.6"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-build-tools",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-client",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-control-panel",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-elasticsearch",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-embedded",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-extensions-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-extensions-junit-platform",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-consul",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-vault",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hivemq",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-kafka",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-dynamodb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-s3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-sns",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-localstack-sqs",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-mongodb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-neo4j",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-opensearch",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mariadb",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mssql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mysql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-free",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-xe",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-pool",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-postgresql",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-rabbitmq",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-redis",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-server",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-solr",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-testcontainers",
          "version": {
            "requires": "2.9.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-test-resources-bom-2.9.0.toml",
          "url": "micronaut-test-resources-bom-2.9.0.toml",
          "size": 10946,
          "sha512": "1765c1afff910b5d37b2d7950cb204b8b5c343f6d22511341c0f8b39b83533be4b1196bd01c33e7692a930bf69ba7ee76e3558bfa548eb0cae19000bab4ee06b",
          "sha256": "24c7603f5bdc6abf3d59c1c4d2979cdd8513e98222feceb82ac6e26ba9ac2b70",
          "sha1": "ce05a9947a834a03f2470c3acc7d5343385da6ae",
          "md5": "fb37e9164c563366c684e56481f2652e"
        }
      ]
    }
  ]
}
