{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-text/1.7.5/ui-text-1.7.5.module",
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-jvmstubs-1.7.5.jar",
          "url": "ui-text-jvmstubs-1.7.5.jar",
          "size": 566161,
          "sha512": "9da1e0e80277adadef6abbb4b9dfc82c72a29682938927b47dd3005e7b0678ff6ee66b6a3e52717dfc9919b8087ccfc79f6177b9a039e9e1f0416d04fef86809",
          "sha256": "4462aaa7f57906f45ab7372cf852780ae9e73e1658afa046625b131419b4e05a",
          "sha1": "418459a82a3384748ee660974f79aefe05dc3932",
          "md5": "14aeb317b8b3ee66a36a2a6815988ef1"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-jvmstubs-1.7.5.jar",
          "url": "ui-text-jvmstubs-1.7.5.jar",
          "size": 566161,
          "sha512": "9da1e0e80277adadef6abbb4b9dfc82c72a29682938927b47dd3005e7b0678ff6ee66b6a3e52717dfc9919b8087ccfc79f6177b9a039e9e1f0416d04fef86809",
          "sha256": "4462aaa7f57906f45ab7372cf852780ae9e73e1658afa046625b131419b4e05a",
          "sha1": "418459a82a3384748ee660974f79aefe05dc3932",
          "md5": "14aeb317b8b3ee66a36a2a6815988ef1"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "ui-text is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-jvmstubs-1.7.5-sources.jar",
          "url": "ui-text-jvmstubs-1.7.5-sources.jar",
          "size": 195409,
          "sha512": "897972e9572350b8fa80335b2d0c506238ffa2a1fa1d1d4f192578412c61bdf1509271e2dc7c3873ad2c5570dafbbe495320ed43fe987727311b2b3eb02210f7",
          "sha256": "3769f1f9853a3daaec7864f3923380aee1ddb55679a86fdd4dbccebda91c461d",
          "sha1": "3063741692a3b03d02ae60f97c58542838c41834",
          "md5": "c6847f01de92106993734f9c92c60daa"
        }
      ]
    }
  ]
}