{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-graphql",
    "version": "3.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.graphql",
          "module": "spring-graphql",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-graphql-3.3.4.jar",
          "url": "spring-boot-starter-graphql-3.3.4.jar",
          "size": 4766,
          "sha512": "11d6ee08cf3d544404df05eb58bb1f6769046863d553a9280579bd2426d317bbd6e0128949d64daed220d41069c05d233d939267919fa3b07ef437f377018b7f",
          "sha256": "873ad21506bd65e5886a117887119f2510f28c69a924e843b4afdda663e5be14",
          "sha1": "f1f6aab98e54d3d458ecaaaca34f2f3173b83341",
          "md5": "7c3f44fe861c3104e6ab9c0240fb6afb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.graphql",
          "module": "spring-graphql",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-graphql-3.3.4.jar",
          "url": "spring-boot-starter-graphql-3.3.4.jar",
          "size": 4766,
          "sha512": "11d6ee08cf3d544404df05eb58bb1f6769046863d553a9280579bd2426d317bbd6e0128949d64daed220d41069c05d233d939267919fa3b07ef437f377018b7f",
          "sha256": "873ad21506bd65e5886a117887119f2510f28c69a924e843b4afdda663e5be14",
          "sha1": "f1f6aab98e54d3d458ecaaaca34f2f3173b83341",
          "md5": "7c3f44fe861c3104e6ab9c0240fb6afb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-graphql-3.3.4-javadoc.jar",
          "url": "spring-boot-starter-graphql-3.3.4-javadoc.jar",
          "size": 4744,
          "sha512": "45260a66f918c1cea03428cba641637aebfa5202d89c8279ad61b4fa04fc42216db95511a41a056499678b0e5b7c7685c9a55d752dcf43d4e135c383e788f60f",
          "sha256": "d5bbdc7b550872615bff06ab349b4c8cffdbc55ec1768dfa32450ec7481262e9",
          "sha1": "f8cf97b124ac0b508df90bcc1fd0e85de7b4caa1",
          "md5": "6e91e765e8f4a52d0e12f6cfe23933bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-graphql-3.3.4-sources.jar",
          "url": "spring-boot-starter-graphql-3.3.4-sources.jar",
          "size": 4743,
          "sha512": "0ae5ba7929d1ec8f3ccae137990ff0e38c1699c0195f376f7409d61e05f179f473234498142b8c3bb6be08dc41e6a25c2ca754a7cba38df94f7633fb2c94539e",
          "sha256": "264cdbe61a77703a5b3ec611f3dffb94020d33335ec34ac30ac6299473108790",
          "sha1": "e8999a6e5496b04c1194c084d8fc5bfe32fd6b81",
          "md5": "f402b977ef2263fa360316ec8a1c7dce"
        }
      ]
    }
  ]
}
