{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.0.20/kotlin-test-2.0.20.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jvmJUnitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.0.20.jar",
          "url": "kotlin-test-junit-2.0.20.jar",
          "size": 5077,
          "sha512": "8eeaa72a367412147daae5dfcad94263982d37ff6af0d25025cf7d475ab2d83caa19a8bc004450870c0d65d01ec7b9da700a953f19e2a7636a20f3fc30f648f2",
          "sha256": "af266a236e9b10d13b0fbd4c8c9662cd5b39d6689b41c9d82cada86822c035c5",
          "sha1": "145bab4a98aec18ac4f4c25282d20c4db70a9132",
          "md5": "e415d8c2b2cc679b9373983bf65ba41f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.20"
        }
      ]
    },
    {
      "name": "jvmJUnitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-2.0.20.jar",
          "url": "kotlin-test-junit-2.0.20.jar",
          "size": 5077,
          "sha512": "8eeaa72a367412147daae5dfcad94263982d37ff6af0d25025cf7d475ab2d83caa19a8bc004450870c0d65d01ec7b9da700a953f19e2a7636a20f3fc30f648f2",
          "sha256": "af266a236e9b10d13b0fbd4c8c9662cd5b39d6689b41c9d82cada86822c035c5",
          "sha1": "145bab4a98aec18ac4f4c25282d20c4db70a9132",
          "md5": "e415d8c2b2cc679b9373983bf65ba41f"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.20"
        }
      ]
    },
    {
      "name": "jvmJUnitSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit-2.0.20-sources.jar",
          "url": "kotlin-test-junit-2.0.20-sources.jar",
          "size": 2830,
          "sha512": "7e646d9971895dd20e122c2a51b0e062d0b03ef898e5886c17baa324ffdb651bf466b7169f828c3dd2f868145ae386f0520b0faa1b7017294742d07e4ebaa4b7",
          "sha256": "c411a0dad1218f3f652b6619f228fefee498903ee6e11c36c990fbc3fe823f18",
          "sha1": "48ca1b92544803c16b9042ae5b5976f6469e0a8c",
          "md5": "ff35307cfd380882a2b7a0d77f06e1b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "2.0.20"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.0.20"
        }
      ]
    }
  ]
}