{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.6.2-multiplatform-sources.jar",
          "url": "foundation-1.6.2-multiplatform-sources.jar",
          "size": 782768,
          "sha512": "169237760829f52d53b3377cbefa26380315d6a206820b20bfd9904b47c0f824ea7d6acc90beded42f46c96c13e100860b154833e4acb37614acac5f29cede43",
          "sha256": "c224cb328b9cb6bc16716d94c8bfb2bd77cbb3b4afb376a60d94281dad7f6c97",
          "sha1": "c87a0c6b6d6d99329e6ef655b0bbf6f76eafc542",
          "md5": "f91e1e2c968c09c2f864aab454ca29fb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-1.6.2-versionMetadata.json",
          "size": 154152,
          "sha512": "9e5b75d000c9bebc5689048a7d10d9811968763cbd1d22ec2c383cac4ddbf2660648413002e07ee558a9fb0d44c65cebb367bf127c897d609c1f999442609839",
          "sha256": "a88df2dc71ebc798e518051a9963038ce740bec24739a3dcb3b5b8abba4c9a63",
          "sha1": "07b15552a2e91e735e483aa098ec0438a63fb696",
          "md5": "ef9b75da32d5a719f7f205eb6c7aea16"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.6.2.jar",
          "url": "foundation-1.6.2.jar",
          "size": 744,
          "sha512": "641669d68fd9c81cbf406435bdb19a9b404b2576a2a84cbb130f14420a9189f91af2a64f1c3046bab297bfa45038b80956ff6477963a960081b84c14feaa8586",
          "sha256": "548f57ae3f6aa9ec87aaac82572f225f99830ec1ece01b622721947c8fb3075d",
          "sha1": "127b46f513500b442bf671026552f81c1c3ccf89",
          "md5": "ca851f221fa1a846318958893c07c55f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.6.2-sources.jar",
          "url": "foundation-1.6.2-sources.jar",
          "size": 666513,
          "sha512": "9d9b9fa9148dbc7315a521521f8ac073004ff58ac8d5ddd986f88f80c0cab83aff8b899acfa378f903d7bd31df7db2afac5887a15a6d09b3d324bf531dd85d29",
          "sha256": "c750378ebd681827c534e621f4bd769effec1265e537b5ae0f0587c718d87340",
          "sha1": "77a4d6e7168457e5cb93cd4e10fd9864fe30dfbb",
          "md5": "70c81e4c87e72e9662bdd6649cf9df03"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.6.2/foundation-android-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.6.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.6.2/foundation-android-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.6.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.6.2/foundation-android-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.6.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.6.2/foundation-desktop-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.6.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.6.2/foundation-desktop-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.6.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-desktop/1.6.2/foundation-desktop-1.6.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-desktop",
        "version": "1.6.2"
      }
    }
  ]
}