{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-stdlib/2.1.20/kotlin-stdlib-2.1.20.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "2.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.1.20.klib",
          "url": "kotlin-stdlib-js-2.1.20.klib",
          "size": 2718730,
          "sha512": "8c046f2e8c466bd0e168407ae379a53d99556464b08873c0bc9fe8451496278dcbcf6bc1b2855403f46f2dc012f988be4a3deb19207a07229a37c9ba2b9b5cb5",
          "sha256": "65a9831cceb606642693f9f3d798de86bbacf09b9588186e763e9e9f3c24d1a3",
          "sha1": "5b335b71e2d6fa1c64b80753498958d18596e43e",
          "md5": "a2b1fe31d5dea5304e957212ca37d1ed"
        }
      ]
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.1.20.klib",
          "url": "kotlin-stdlib-js-2.1.20.klib",
          "size": 2718730,
          "sha512": "8c046f2e8c466bd0e168407ae379a53d99556464b08873c0bc9fe8451496278dcbcf6bc1b2855403f46f2dc012f988be4a3deb19207a07229a37c9ba2b9b5cb5",
          "sha256": "65a9831cceb606642693f9f3d798de86bbacf09b9588186e763e9e9f3c24d1a3",
          "sha1": "5b335b71e2d6fa1c64b80753498958d18596e43e",
          "md5": "a2b1fe31d5dea5304e957212ca37d1ed"
        }
      ]
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-stdlib-js-2.1.20-sources.jar",
          "url": "kotlin-stdlib-js-2.1.20-sources.jar",
          "size": 687450,
          "sha512": "eb770ac183f432bb3f922626c16a83e2345d634fc47c146c47ef7f2a35b33594cdd04632667d7805fa130a3d74708633b72250559034a1819a350cf1ae64ef49",
          "sha256": "b5ed661d6b0a87322e0a7881aae89b078b3c0b23b1aae87811480b94d3e77ac8",
          "sha1": "648b8faa349be29d664712a20f9fb330b3c1b1fe",
          "md5": "50082746538e5bc7d63efe087ca315d9"
        }
      ]
    }
  ]
}
