{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.3.1/material3-1.3.1.module",
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-desktop-1.3.1.jar",
          "url": "material3-desktop-1.3.1.jar",
          "size": 3627828,
          "sha512": "3f7ffcd09f4a005ece771d044c4e0254d72d4f9104ebc5605a443c77dad21985d183fcd94bb2edaaf16f1204c87730a2ae2e6420a43cf79966acdba1f6f75ac3",
          "sha256": "d58cb83edc6271d30d25882f5ecba765aaafe60b7dd88b6adec99881bc8801ab",
          "sha1": "1053f80b12da9bdd2157944d5803b0ad1715801b",
          "md5": "cf17f673f4427af9007044c09378b8b5"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-desktop-1.3.1.jar",
          "url": "material3-desktop-1.3.1.jar",
          "size": 3627828,
          "sha512": "3f7ffcd09f4a005ece771d044c4e0254d72d4f9104ebc5605a443c77dad21985d183fcd94bb2edaaf16f1204c87730a2ae2e6420a43cf79966acdba1f6f75ac3",
          "sha256": "d58cb83edc6271d30d25882f5ecba765aaafe60b7dd88b6adec99881bc8801ab",
          "sha1": "1053f80b12da9bdd2157944d5803b0ad1715801b",
          "md5": "cf17f673f4427af9007044c09378b8b5"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-desktop-1.3.1-sources.jar",
          "url": "material3-desktop-1.3.1-sources.jar",
          "size": 470495,
          "sha512": "ef946aeee872677204e3de76e5fb3c26388690c31ebed9f1803f4d44d095c851da8c671e19c6e253d25c3fc695087b6c3f42b71eec882e82f06ed11b990ef48e",
          "sha256": "fb440f8c3e445bf203b93e5b85a6d90858c8a0104daf7ef9867b6fc86a36be85",
          "sha1": "07f1ad7e538d860bb0fcff4b47252b5f91e19971",
          "md5": "871b9d53539b4c33e8c27276c64bfe93"
        }
      ]
    }
  ]
}