{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.6.2/foundation-1.6.2.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.6.2.jar",
          "url": "foundation-desktop-1.6.2.jar",
          "size": 3518887,
          "sha512": "ad01d58aaee9992cb9a13e4f7f59a1cf84361223f408dae61adcf24f886268863321e6e98671988143157951af7df94cd76dc4de10ac155ac98a0b405d9c5a38",
          "sha256": "1eda12bee5a9660ba703ebb3bb38a2ef57011fdc8f4cbcce0d0d7da02cd0a8d0",
          "sha1": "d7267e1684e6a5f2d8ea6c47a315f429d02409fd",
          "md5": "71faac0f0ecab1c770a75e5dd2287918"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.6.2.jar",
          "url": "foundation-desktop-1.6.2.jar",
          "size": 3518887,
          "sha512": "ad01d58aaee9992cb9a13e4f7f59a1cf84361223f408dae61adcf24f886268863321e6e98671988143157951af7df94cd76dc4de10ac155ac98a0b405d9c5a38",
          "sha256": "1eda12bee5a9660ba703ebb3bb38a2ef57011fdc8f4cbcce0d0d7da02cd0a8d0",
          "sha1": "d7267e1684e6a5f2d8ea6c47a315f429d02409fd",
          "md5": "71faac0f0ecab1c770a75e5dd2287918"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.6.2-sources.jar",
          "url": "foundation-desktop-1.6.2-sources.jar",
          "size": 708633,
          "sha512": "73e285db8f51d6c0dea3baf1fbfc7d4b78f3e61571160ffe567bb3c86f62d7f6a615d3573ebd8c91839a0892ded06dd5028ae5cc2fbd82c6698a9e1d8691178f",
          "sha256": "36c36436c66d76e80fd244921dd59c6a36ae6a29da6cbe0091d1fef504434a4c",
          "sha1": "2eeb7d56243521ad48d2997ce58446f3c1e780ec",
          "md5": "51aaf0f1bf78e6b6fc900a60c1332d38"
        }
      ]
    }
  ]
}