{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.email",
    "module": "micronaut-email-bom",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.eclipse.angus",
          "module": "angus-mail",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "jakarta.mail",
          "module": "jakarta.mail-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.mailjet",
          "module": "mailjet-client",
          "version": {
            "requires": "5.2.6"
          }
        },
        {
          "group": "com.postmarkapp",
          "module": "postmark",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "com.sendgrid",
          "module": "sendgrid-java",
          "version": {
            "requires": "4.10.3"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-amazon-ses",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-javamail",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-javamail-composer",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-mailjet",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-postmark",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-sendgrid",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-template",
          "version": {
            "requires": "2.9.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.eclipse.angus",
          "module": "angus-mail",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "jakarta.mail",
          "module": "jakarta.mail-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.mailjet",
          "module": "mailjet-client",
          "version": {
            "requires": "5.2.6"
          }
        },
        {
          "group": "com.postmarkapp",
          "module": "postmark",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "com.sendgrid",
          "module": "sendgrid-java",
          "version": {
            "requires": "4.10.3"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-amazon-ses",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-javamail",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-javamail-composer",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-mailjet",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-postmark",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-sendgrid",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.micronaut.email",
          "module": "micronaut-email-template",
          "version": {
            "requires": "2.9.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-email-bom-2.9.0.toml",
          "url": "micronaut-email-bom-2.9.0.toml",
          "size": 1878,
          "sha512": "451f6299690cf6798b0c4f636863fb9b33a2544876216b4dae2ab2a68e44f872f7627bca3e7808783d12cbf81ebbeabc57cf5b397b72a4875e2cc5dc36d976d9",
          "sha256": "2b19a89668b0e330c14ebb1e433d1746d3bbfe1a86cbe4cb713f4b614812c26f",
          "sha1": "20fe7de1becebe2e921f00c5ab293ee195722869",
          "md5": "127edd50a7a55b696753537ff779f591"
        }
      ]
    }
  ]
}
