{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.0.M3/kotest-assertions-shared-6.0.0.M3.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.0.M3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0.M3.klib",
          "url": "kotest-assertions-shared-js-6.0.0.M3.klib",
          "size": 528889,
          "sha512": "0524e8315e705160e3fc22dbf01284ef9607cfe0c8a3a3c44429f11be7a873f3c60a5f1c5c1d79a8eadf16ccbb19735b51a97ae3a86378b823f9560333f025bc",
          "sha256": "3ba10f24f467ff0c100e640d2e4166224724ca3f8893ae6a95258689c7c522bb",
          "sha1": "52304e94c11e56c0368a5e9506c7068210e753d9",
          "md5": "e62924553809d286a17e2b1811bf4ba6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.0.M3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0.M3.klib",
          "url": "kotest-assertions-shared-js-6.0.0.M3.klib",
          "size": 528889,
          "sha512": "0524e8315e705160e3fc22dbf01284ef9607cfe0c8a3a3c44429f11be7a873f3c60a5f1c5c1d79a8eadf16ccbb19735b51a97ae3a86378b823f9560333f025bc",
          "sha256": "3ba10f24f467ff0c100e640d2e4166224724ca3f8893ae6a95258689c7c522bb",
          "sha1": "52304e94c11e56c0368a5e9506c7068210e753d9",
          "md5": "e62924553809d286a17e2b1811bf4ba6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-js-6.0.0.M3-sources.jar",
          "url": "kotest-assertions-shared-js-6.0.0.M3-sources.jar",
          "size": 77524,
          "sha512": "04d6bc17ede85fd30ffd5742bb5a8ba925d0f6255a07009d6381b883ac2db16be5595ca009d31e0f0c787a4b4a79bd30cb6915fdab659c1b3c8bc952169ac5e6",
          "sha256": "98cc308e40a525a0db4992a3c15a171f6c4db4f2447092f234d47f7a9e5f5e02",
          "sha1": "7e63c5571de5323882b1b1a387dfb37acb06b542",
          "md5": "290727f9303655e6205716f87c140b44"
        }
      ]
    }
  ]
}
