{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.10.0/kotlinx-coroutines-core-1.10.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-js",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-js-1.10.0.klib",
          "url": "kotlinx-coroutines-core-js-1.10.0.klib",
          "size": 853797,
          "sha512": "49279fb9fbba844801aef60a59c6aa89c21ce935053ce45c96538e706756828c3c0bf372ecce8dcfd3875756b001602a955e5f88de5fd35cafff292da9e6edaf",
          "sha256": "efc770fac6a39d3d677dd7b426962392bbaebb2b0a9cb44434e45fdc06162791",
          "sha1": "9fdec16fb4ec15cdb1aefa17a139992772084fe7",
          "md5": "d84a702a69350902874e0f09bc915c4f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-js",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-js-1.10.0.klib",
          "url": "kotlinx-coroutines-core-js-1.10.0.klib",
          "size": 853797,
          "sha512": "49279fb9fbba844801aef60a59c6aa89c21ce935053ce45c96538e706756828c3c0bf372ecce8dcfd3875756b001602a955e5f88de5fd35cafff292da9e6edaf",
          "sha256": "efc770fac6a39d3d677dd7b426962392bbaebb2b0a9cb44434e45fdc06162791",
          "sha1": "9fdec16fb4ec15cdb1aefa17a139992772084fe7",
          "md5": "d84a702a69350902874e0f09bc915c4f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-js-1.10.0-sources.jar",
          "url": "kotlinx-coroutines-core-js-1.10.0-sources.jar",
          "size": 317590,
          "sha512": "f9c1cc2ad3e38001a6cf98acef864ef663da2be5b5ca99efc08151b022aa275576e29660bc830cd200f345f0231e655c63fd147421725158c37b565ae9c7130c",
          "sha256": "fe679a7edf1b4e637aac6681e74e47b719b2b57bd065f1671d6cda77e97f5f83",
          "sha1": "e5788eb04bc374afc51214a3b0d5e1c9300ceec2",
          "md5": "ee9bff2024d73b6fb98628417a60fbbd"
        }
      ]
    }
  ]
}
