{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.graphql",
    "module": "spring-graphql",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-graphql-1.3.2.jar",
          "url": "spring-graphql-1.3.2.jar",
          "size": 626587,
          "sha512": "90ee4daabd8ba34c315d5a022203d257abe91b777b89b49cce6b0ac4a3ffc27a84167f9ef92297dbd01ef05a7a15058a70388df5c159c16f0869648d44e4de82",
          "sha256": "0e610d534c1f84ba41ad353514cd0be99bbd540f39749c435747709deed2a48f",
          "sha1": "1752565a76cdf53a0ae91288e812ae52d4fbe3fa",
          "md5": "19656621faacb4a4274273de2b83b932"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "context-propagation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "22.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-graphql-1.3.2.jar",
          "url": "spring-graphql-1.3.2.jar",
          "size": 626587,
          "sha512": "90ee4daabd8ba34c315d5a022203d257abe91b777b89b49cce6b0ac4a3ffc27a84167f9ef92297dbd01ef05a7a15058a70388df5c159c16f0869648d44e4de82",
          "sha256": "0e610d534c1f84ba41ad353514cd0be99bbd540f39749c435747709deed2a48f",
          "sha1": "1752565a76cdf53a0ae91288e812ae52d4fbe3fa",
          "md5": "19656621faacb4a4274273de2b83b932"
        }
      ]
    }
  ]
}
